version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773
      - 52773:52773
      - 53773
    #command: --up false
    environment: 
      ISC_DATA_DIRECTORY: /external/conf
    volumes:
      - ./:/irisdev/app
      - ./share/:/tmp/share
      - fhiraas_external:/external

volumes:
  fhiraas_external: {}